### PR TITLE
Block only the actual errortrace-key

### PR DESCRIPTION
**Pull request by sorawee**
There's no need to block all modules named errortrace-key.
We can test if the target form is from errortrace-key by checking
syntax-source and see if it's equal resolve-module-path of
'errortrace/errortrace-key

### CODE REVIEW

**Comment by sorawee** [comment]
Conflict resolved.

**Comment by sorawee** [comment]
Oops, I didn't mean to close this PR. I accidentally deleted the repo.

Let me know if anyone wants to merge this, and I will submit it again.

**Comment by samth** [comment]
Seems like an improvement to me.

**Comment by sorawee** [comment]
I rebased the branch but the PR no longer tracks the branch. I think I need to submit a new one for it to work properly.

**Comment by rfindler** [comment]
I considered changing this with my earlier commit but I could not get bad behavior to happen. But a proper change is to use the new name parameter, which will require some threading (perhaps adding a new predicate to the newly added signature?)

**Comment by sorawee** [comment]
Yeah, me too. I tried to provoke a bad behavior and could not do so. Though I recall I could do it when I first submitted the PR (I could be wrong however -- that was long ago).

**Comment by rfindler** [comment]
Wow, it sure was a long time ago!

**Pull request closed without merging**
