### PR TITLE
Make #lang errortrace support REPL

### LINKED ISSUE #31: VSCode Load File in REPL error: readline-input:1:0: #%top-interaction: unbound identifier
When I use the Load File in REPL command on an otherwise empty Racket file:

```racket
#lang errortrace racket
```

It runs the following command:

`racket --repl --eval '(enter! (file "/Users/gus/tmp0.rkt"))'`

The REPL loads, but when I run any command in the REPL I get the following error:

```
"racket/tmp0.rkt"> 1
; readline-input:1:0: #%top-interaction: unbound identifier;
;  also, no #%app syntax transformer is bound
;   at: #%top-interaction
;   in: (#%top-interaction . 1)
; [,bt for context]
```

Can this be fixed?

### PR DESCRIPTION
**Pull request by sorawee**
This is done by making `#lang errortrace` adjust `current-compile`
(loaded by requiring `errortrace`) instead of creating a custom expander
that manually annotates the program. Since we simply modify `current-compile`,
the effective expander is that specified by users, so the REPL is
still functional.

Fixes #31

### CODE REVIEW

**Comment by sorawee** [comment]
I added a test.

**Comment by rfindler** [comment]
Would the test case also work with just `(dynamic-require "lang.rkt" #f)`, possibly in a new base namespace?

**Comment by sorawee** [comment]
How do I interact with the REPL of `lang.rkt` after `dynamic-require`?

In any case, I think this PR is currently blocked by https://github.com/racket/racket/issues/4362.

**Comment by rfindler** [comment]
You make a namespace with module->namespace and set it as the current
namespace. Then call eval with whatever you'd type into the repl.

Robby

**Comment by sorawee** [comment]
Ah, that works indeed, but note that I need to wrap things with `#%top-interaction` explicitly to test that `#%top-interaction` is functional.

**Comment by rfindler** [comment]
You could set the parameters and call `read-eval-print-loop` with `current-input-port` set to the result of `open-input-string`, maybe?

**Pull request merged**
